/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Dark_Room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function DarkRoom(props) {
  const { nodes, materials } = useGLTF('/models/Dark_Room/Dark_Room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 4.603, 0.035]} scale={3.859}>
        <mesh geometry={nodes.Cube.geometry} material={materials.walls} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Seat} />
        <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.Seat2} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials.metalblack} />
        <mesh geometry={nodes.Cube_6.geometry} material={materials.Tires} />
        <mesh geometry={nodes.Cube_7.geometry} material={materials['table 2']} />
        <mesh geometry={nodes.Cube_8.geometry} material={materials.wall_emission} />
        <mesh geometry={nodes.Cube_9.geometry} material={materials['wall_emission.003']} />
        <mesh geometry={nodes.Cube_10.geometry} material={materials.tv_table} />
        <mesh geometry={nodes.Cube_11.geometry} material={materials.Mousepad} />
        <mesh geometry={nodes.Cube_12.geometry} material={materials.emmision} />
        <mesh geometry={nodes.Cube_13.geometry} material={materials.keyboard} />
        <mesh geometry={nodes.Cube_14.geometry} material={materials.KB3} />
        <mesh geometry={nodes.Cube_15.geometry} material={materials.headphones} />
        <mesh geometry={nodes.Cube_16.geometry} material={materials.KEY} />
        <mesh geometry={nodes.Cube_17.geometry} material={materials['kb2 emission']} />
        <mesh geometry={nodes.Cube_18.geometry} material={materials.tv} />
        <mesh geometry={nodes.Cube_19.geometry} material={materials.rED} />
        <mesh geometry={nodes.Cube_20.geometry} material={materials.screen} />
        <mesh geometry={nodes.Cube_21.geometry} material={materials['B emmision']} />
        <mesh geometry={nodes.Cube_22.geometry} material={materials.speaker} />
        <mesh geometry={nodes.Cube_23.geometry} material={materials.speaker2} />
        <mesh geometry={nodes.Cube_24.geometry} material={materials.bOOK1} />
        <mesh geometry={nodes.Cube_25.geometry} material={materials.bOOKS} />
        <mesh geometry={nodes.Cube_26.geometry} material={materials.BOOK2} />
        <mesh geometry={nodes.Cube_27.geometry} material={materials.bOOK5} />
        <mesh geometry={nodes.Cube_28.geometry} material={materials.bOOK4} />
        <mesh geometry={nodes.Cube_29.geometry} material={materials.bOOK} />
        <mesh geometry={nodes.Cube_30.geometry} material={materials.PS5} />
        <mesh geometry={nodes.Cube_31.geometry} material={materials.Controller} />
        <mesh geometry={nodes.Cube_32.geometry} material={materials.ps5} />
        <mesh geometry={nodes.Cube_33.geometry} material={materials['Ps5 emmision']} />
        <mesh geometry={nodes.Cube_34.geometry} material={materials.Buttons} />
        <mesh geometry={nodes.Cube_35.geometry} material={materials.Bed} />
        <mesh geometry={nodes.Cube_36.geometry} material={materials.bed2} />
        <mesh geometry={nodes.Cube_37.geometry} material={materials.bedhseet} />
        <mesh geometry={nodes.Cube_38.geometry} material={materials['Headphones red']} />
        <mesh geometry={nodes.Cube_39.geometry} material={materials.table} />
        <mesh geometry={nodes.Cube_40.geometry} material={materials.cpu} />
        <mesh geometry={nodes.Cube_41.geometry} material={materials['637151']} />
        <mesh geometry={nodes.Cube_42.geometry} material={materials.Poster} />
        <mesh geometry={nodes.Cube_43.geometry} material={materials['fan emmision']} />
        <mesh geometry={nodes.Cube_44.geometry} material={materials['vegeta-ssjg-super-saiyan-god-from-dragon-ball_5760x3240_xtrafon']} />
        <mesh geometry={nodes.Cube_45.geometry} material={materials['wp4113638-goku-ssj-ultra-wallpapers']} />
        <mesh geometry={nodes.Cube_46.geometry} material={materials['Cpu glass']} />
        <mesh geometry={nodes.Cube_47.geometry} material={materials['black wood']} />
        <mesh geometry={nodes.Cube_48.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_49.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_50.geometry} material={materials.carpet} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.plane} position={[0, 0.149, 0]} scale={38.205} />
      <mesh geometry={nodes.Sofa.geometry} material={materials.sofa} position={[1.007, 1.315, -0.401]} rotation={[0, 0, -Math.PI]} scale={[-1.666, -0.589, -0.109]}>
        <mesh geometry={nodes.Sofa002.geometry} material={materials.sofa} position={[0, -0.764, 6.26]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.964, 5.414, 0.245]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/Dark_Room/Dark_Room.glb')
