/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Light_Room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LightRoom(props) {
  const { nodes, materials } = useGLTF('/models/Light_Room/Light_Room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.299, 1.451, -0.379]} rotation={[Math.PI, 0, Math.PI]} scale={1.552}>
        <group position={[-0.007, 0.191, 0.004]} scale={1.637}>
          <mesh geometry={nodes.part_1001.geometry} material={materials['cactus_gasteria_vase_gasteria.003']} />
          <mesh geometry={nodes.part_1001_1.geometry} material={materials['cactus_gasteria_cactus_gasteria.003']} />
          <mesh geometry={nodes.part_1001_2.geometry} material={materials['cactus_gasteria_clay_pot.003']} />
          <mesh geometry={nodes.part_1001_3.geometry} material={materials['cactus_gasteria_ground_pot5.003']} />
          <mesh geometry={nodes.part_1001_4.geometry} material={materials['cactus_gasteria_stones.003']} />
          <mesh geometry={nodes.part_1001_5.geometry} material={materials['tapis 18.001']} />
          <mesh geometry={nodes.part_1001_6.geometry} material={materials['Galho seco .001']} />
          <mesh geometry={nodes.part_1001_7.geometry} material={materials['golden metal.001']} />
          <mesh geometry={nodes.part_1001_8.geometry} material={materials['white ceramic.001']} />
          <mesh geometry={nodes.part_1001_9.geometry} material={materials['Candle Wax.001']} />
          <mesh geometry={nodes.part_1001_10.geometry} material={materials['metal.001']} />
          <mesh geometry={nodes.part_1001_11.geometry} material={materials['kindpng_1178585.001']} />
          <mesh geometry={nodes.part_1001_12.geometry} material={materials['Rope.001']} />
          <mesh geometry={nodes.part_1001_13.geometry} material={materials['Ceramica off white.002']} />
          <mesh geometry={nodes.part_1001_14.geometry} material={materials['Ceramica off white.003']} />
          <mesh geometry={nodes.part_1001_15.geometry} material={materials['Bamboo fine wood PBR texture seamless.001']} />
          <mesh geometry={nodes.part_1001_16.geometry} material={materials['Brushed  Copper.001']} />
          <mesh geometry={nodes.part_1001_17.geometry} material={materials['Fabric Beige.001']} />
          <mesh geometry={nodes.part_1001_18.geometry} material={materials['BlacK Blur.001']} />
          <mesh geometry={nodes.part_1001_19.geometry} material={materials['Wood_2k.001']} />
        </group>
      </group>
      <group position={[-3.859, 2.339, 0.046]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <group position={[-0.02, 0.051, -0.75]} scale={0.82}>
          <mesh geometry={nodes.part_4001.geometry} material={materials['Canvas.002']} />
          <mesh geometry={nodes.part_4001_1.geometry} material={materials['Metal.003']} />
          <mesh geometry={nodes.part_4001_2.geometry} material={materials['Golden Oak.002']} />
          <mesh geometry={nodes.part_4001_3.geometry} material={materials['Unfinished.002']} />
          <mesh geometry={nodes.part_4001_4.geometry} material={materials['Painting Art 10.002']} />
          <mesh geometry={nodes.part_4001_5.geometry} material={materials['QUADRO MINIMALISTA G.001']} />
          <mesh geometry={nodes.part_4001_6.geometry} material={materials['Pic_Glass.001']} />
          <mesh geometry={nodes.part_4001_7.geometry} material={materials['Pic_Wood White.001']} />
          <mesh geometry={nodes.part_4001_8.geometry} material={materials['Pic_Wood Brown.001']} />
          <mesh geometry={nodes.part_4001_9.geometry} material={materials['Pic_Painting.001']} />
          <mesh geometry={nodes.part_4001_10.geometry} material={materials['abstract art.001']} />
          <mesh geometry={nodes.part_4001_11.geometry} material={materials['Photo.001']} />
          <mesh geometry={nodes.part_4001_12.geometry} material={materials['Wood.002']} />
          <mesh geometry={nodes.part_4001_13.geometry} material={materials['Inside.001']} />
          <mesh geometry={nodes.part_4001_14.geometry} material={materials['Gold.001']} />
          <mesh geometry={nodes.part_4001_15.geometry} material={materials['Dante_wood.001']} />
          <mesh geometry={nodes.part_4001_16.geometry} material={materials['Poster_bauhaus.001']} />
          <mesh geometry={nodes.part_4001_17.geometry} material={materials['stackofbooks.001']} />
          <mesh geometry={nodes.part_4001_18.geometry} material={materials['Books.001']} />
          <mesh geometry={nodes.part_4001_19.geometry} material={materials['Pine Wood.001']} />
          <mesh geometry={nodes.part_4001_20.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.part_4001_21.geometry} material={materials['Material.014']} />
          <mesh geometry={nodes.part_4001_22.geometry} material={materials['Material.018']} />
          <mesh geometry={nodes.part_4001_23.geometry} material={materials['Door.002']} />
          <mesh geometry={nodes.part_4001_24.geometry} material={materials['Box.002']} />
          <mesh geometry={nodes.part_4001_25.geometry} material={materials['Box.003']} />
          <mesh geometry={nodes.part_4001_26.geometry} material={materials['Door.003']} />
          <mesh geometry={nodes.part_4001_27.geometry} material={materials['Post-It Notes.001']} />
          <mesh geometry={nodes.part_4001_28.geometry} material={materials['cactus.001']} />
          <mesh geometry={nodes.part_4001_29.geometry} material={materials['Ground.001']} />
          <mesh geometry={nodes.part_4001_30.geometry} material={materials['spike base.001']} />
          <mesh geometry={nodes.part_4001_31.geometry} material={materials['spikes.001']} />
          <mesh geometry={nodes.part_4001_32.geometry} material={materials['clay.001']} />
          <mesh geometry={nodes.part_4001_33.geometry} material={materials['cactus_gasteria_vase_gasteria.004']} />
          <mesh geometry={nodes.part_4001_34.geometry} material={materials['cactus_gasteria_cactus_gasteria.004']} />
          <mesh geometry={nodes.part_4001_35.geometry} material={materials['cactus_gasteria_clay_pot.004']} />
          <mesh geometry={nodes.part_4001_36.geometry} material={materials['cactus_gasteria_ground_pot5.004']} />
          <mesh geometry={nodes.part_4001_37.geometry} material={materials['cactus_gasteria_stones.004']} />
          <mesh geometry={nodes.part_4001_38.geometry} material={materials['pine.001']} />
          <mesh geometry={nodes.part_4001_39.geometry} material={materials['Fiber.001']} />
          <mesh geometry={nodes.part_4001_40.geometry} material={materials['FIber Alpha.001']} />
          <mesh geometry={nodes.part_4001_41.geometry} material={materials['Glazed ceramic.002']} />
          <mesh geometry={nodes.part_4001_42.geometry} material={materials['Soil_1.001']} />
          <mesh geometry={nodes.part_4001_43.geometry} material={materials['Daun.001']} />
        </group>
      </group>
      <group position={[0, 4.629, 0.099]} scale={3.859}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.walls} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.laminate_floor_02} />
      </group>
      <group position={[-3.275, 2.173, 1.481]} rotation={[0, -Math.PI / 2, 0]} scale={1.735}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Plastic - Black']} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Silver - Matte']} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Grey Metal']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Wheels - Black']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder011_5.geometry} material={materials['Cushion Material']} />
        <mesh geometry={nodes.Cylinder011_6.geometry} material={materials['White Melamine']} />
        <mesh geometry={nodes.Cylinder011_7.geometry} material={materials['Wood Finished']} />
        <mesh geometry={nodes.Cylinder011_8.geometry} material={materials['Rose Gold Metal']} />
        <mesh geometry={nodes.Cylinder011_9.geometry} material={materials['Gray white plastic']} />
        <mesh geometry={nodes.Cylinder011_10.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder011_11.geometry} material={materials['Steel round brushed']} />
        <mesh geometry={nodes.Cylinder011_12.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_13.geometry} material={materials['IMac-Body']} />
        <mesh geometry={nodes.Cylinder011_14.geometry} material={materials.MetalExterior} />
        <mesh geometry={nodes.Cylinder011_15.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cylinder011_16.geometry} material={materials.Bezel} />
        <mesh geometry={nodes.Cylinder011_17.geometry} material={materials.MaschinedMetal} />
        <mesh geometry={nodes.Cylinder011_18.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cylinder011_19.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cylinder011_20.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cylinder011_21.geometry} material={materials.Body} />
        <mesh geometry={nodes.Cylinder011_22.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cylinder011_23.geometry} material={materials['Metal.001']} />
        <mesh geometry={nodes.Cylinder011_24.geometry} material={materials['black cover.001']} />
        <mesh geometry={nodes.Cylinder011_25.geometry} material={materials['black cover']} />
        <mesh geometry={nodes.Cylinder011_26.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cylinder011_27.geometry} material={materials['top and bottom side']} />
        <mesh geometry={nodes.Cylinder011_28.geometry} material={materials['papper stack texture']} />
        <mesh geometry={nodes.Cylinder011_29.geometry} material={materials['glossy metal']} />
        <mesh geometry={nodes.Cylinder011_30.geometry} material={materials['16_Body_1_black']} />
        <mesh geometry={nodes.Cylinder011_31.geometry} material={materials['16_Body_2_black']} />
        <mesh geometry={nodes.Cylinder011_32.geometry} material={materials['16_Body_3_black']} />
        <mesh geometry={nodes.Cylinder011_33.geometry} material={materials['16_Body_4_black']} />
        <mesh geometry={nodes.Cylinder011_34.geometry} material={materials['16_apple_black']} />
        <mesh geometry={nodes.Cylinder011_35.geometry} material={materials['16_black']} />
        <mesh geometry={nodes.Cylinder011_36.geometry} material={materials['16_cam2']} />
        <mesh geometry={nodes.Cylinder011_37.geometry} material={materials['16_lens']} />
        <mesh geometry={nodes.Cylinder011_38.geometry} material={materials['16_screen']} />
        <mesh geometry={nodes.Cylinder011_39.geometry} material={materials['16_Glass']} />
        <mesh geometry={nodes.Cylinder011_40.geometry} material={materials['16_wire']} />
        <mesh geometry={nodes.Cylinder011_41.geometry} material={materials['16_1111']} />
        <mesh geometry={nodes.Cylinder011_42.geometry} material={materials['16_16fs']} />
        <mesh geometry={nodes.Cylinder011_43.geometry} material={materials['16_16fs1']} />
        <mesh geometry={nodes.Cylinder011_44.geometry} material={materials['16_g']} />
        <mesh geometry={nodes.Cylinder011_45.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cylinder011_46.geometry} material={materials['Flame.001']} />
      </group>
      <group position={[0.751, 2.528, -3.438]}>
        <mesh geometry={nodes.Mesh041.geometry} material={materials['LED.4500K']} />
        <mesh geometry={nodes.Mesh041_1.geometry} material={materials.pot} />
        <mesh geometry={nodes.Mesh041_2.geometry} material={materials.GROUND} />
        <mesh geometry={nodes.Mesh041_3.geometry} material={materials['leaf.001']} />
        <mesh geometry={nodes.Mesh041_4.geometry} material={materials['trunk.001']} />
        <mesh geometry={nodes.Mesh041_5.geometry} material={materials.torso_of_a_woman_Iris} />
        <mesh geometry={nodes.Mesh041_6.geometry} material={materials['Ceramic.Black']} />
        <mesh geometry={nodes.Mesh041_7.geometry} material={materials['Metal.Brzone']} />
        <mesh geometry={nodes.Mesh041_8.geometry} material={materials['Ceramic.black']} />
        <mesh geometry={nodes.Mesh041_9.geometry} material={materials.Horus} />
        <mesh geometry={nodes.Mesh041_10.geometry} material={materials['Old Greek style flower pot']} />
        <mesh geometry={nodes.Mesh041_11.geometry} material={materials['NA Aluminium']} />
        <mesh geometry={nodes.Mesh041_12.geometry} material={materials.Gasket} />
        <mesh geometry={nodes.Mesh041_13.geometry} material={materials['Window Glass']} />
        <mesh geometry={nodes.Mesh041_14.geometry} material={materials['scan texture.001']} />
        <mesh geometry={nodes.Mesh041_15.geometry} material={materials['ALUMINIUM.004']} />
        <mesh geometry={nodes.Mesh041_16.geometry} material={materials['oak wood.004']} />
        <mesh geometry={nodes.Mesh041_17.geometry} material={materials['ALUMINIUM.002']} />
        <mesh geometry={nodes.Mesh041_18.geometry} material={materials['oak wood.002']} />
        <mesh geometry={nodes.Mesh041_19.geometry} material={materials['ALUMINIUM.003']} />
        <mesh geometry={nodes.Mesh041_20.geometry} material={materials['oak wood.003']} />
        <mesh geometry={nodes.Mesh041_21.geometry} material={materials['ALUMINIUM.005']} />
        <mesh geometry={nodes.Mesh041_22.geometry} material={materials['oak wood.005']} />
        <mesh geometry={nodes.Mesh041_23.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Mesh041_24.geometry} material={materials['Greasy wood.002']} />
        <mesh geometry={nodes.Mesh041_25.geometry} material={materials['Fabric Upholstery 001a']} />
        <mesh geometry={nodes.Mesh041_26.geometry} material={materials['cactus_gasteria_vase_gasteria.001']} />
        <mesh geometry={nodes.Mesh041_27.geometry} material={materials['cactus_gasteria_cactus_gasteria.001']} />
        <mesh geometry={nodes.Mesh041_28.geometry} material={materials['cactus_gasteria_clay_pot.001']} />
        <mesh geometry={nodes.Mesh041_29.geometry} material={materials['cactus_gasteria_ground_pot5.001']} />
        <mesh geometry={nodes.Mesh041_30.geometry} material={materials['cactus_gasteria_stones.001']} />
        <mesh geometry={nodes.Mesh041_31.geometry} material={materials['Fiber.002']} />
        <mesh geometry={nodes.Mesh041_32.geometry} material={materials['FIber Alpha.002']} />
        <mesh geometry={nodes.Mesh041_33.geometry} material={materials['Glazed ceramic.001']} />
        <mesh geometry={nodes.Mesh041_34.geometry} material={materials['Soil_1.002']} />
        <mesh geometry={nodes.Mesh041_35.geometry} material={materials['Daun.002']} />
        <mesh geometry={nodes.Mesh041_36.geometry} material={materials['torso_of_a_woman_Iris.002']} />
        <mesh geometry={nodes.Mesh041_37.geometry} material={materials['008_Column.001']} />
        <mesh geometry={nodes.Mesh041_38.geometry} material={materials['scan texture.002']} />
        <mesh geometry={nodes.Mesh041_39.geometry} material={materials['vase-cross.001']} />
        <mesh geometry={nodes.Mesh041_40.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.Mesh041_41.geometry} material={materials['stem.001']} />
        <mesh geometry={nodes.Mesh041_42.geometry} material={materials['dirt.001']} />
        <mesh geometry={nodes.Mesh041_43.geometry} material={materials['Clay Orange']} />
        <mesh geometry={nodes.Mesh041_44.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh041_45.geometry} material={materials.Schnittlauch} />
        <mesh geometry={nodes.Mesh041_46.geometry} material={materials['Clay Orange.001']} />
        <mesh geometry={nodes.Mesh041_47.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Mesh041_48.geometry} material={materials['Schnittlauch.001']} />
        <mesh geometry={nodes.Mesh041_49.geometry} material={materials['Clay Orange.002']} />
        <mesh geometry={nodes.Mesh041_50.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Mesh041_51.geometry} material={materials['Schnittlauch.002']} />
        <mesh geometry={nodes.Mesh041_52.geometry} material={materials['Clay Orange.003']} />
        <mesh geometry={nodes.Mesh041_53.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Mesh041_54.geometry} material={materials['Schnittlauch.003']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['plane.001']} position={[0, 0.149, 0]} scale={38.205} />
    </group>
  )
}

useGLTF.preload('/models/Light_Room/Light_Room.glb')
